version: '3'
services:
  n8n:
    image: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.example.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user  # กำหนดผู้ใช้
      - N8N_BASIC_AUTH_PASSWORD=password  # กำหนดรหัสผ่าน
    volumes:
      - ./.n8n:/home/node/.n8n
